name: Docker Multi-Architecture Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

jobs:
  build-jdk:
    uses: ./.github/workflows/fat-build.yml

  build-docker:
    needs: build-jdk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
#          - image: 1337kavin/piped:openj9
#            dockerfile: ./Dockerfile.openj9.ci
          - image: ghcr.io/${{ github.repository }}:hotspot
            dockerfile: ./Dockerfile.ci
          - image: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:azul-zulu
            dockerfile: ./Dockerfile.azul.ci
          - image: ghcr.io/${{ github.repository }}:graalvm-jvm
            dockerfile: ./Dockerfile.graalvm-jvm.ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: piped.jar
      - name: Create Version File
        run: echo $(git log -1 --date=short --pretty=format:%cd)-$(git rev-parse --short HEAD) > VERSION
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: Login to GitHub's Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
